# .github/workflows/build-css.yml
name: Build & Deploy Tailwind CSS

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write    # allow the GITHUB_TOKEN to push commits

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'    # optional: caches ~/.npm to speed installs

      - name: Install dependencies
        run: npm install

      - name: Build CSS
        run: npm run build:css
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Commit compiled CSS
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: rebuild Tailwind CSS"
          file_pattern: css/styles.css
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
