name: Deploy to GitHub Pages

# Fires when the Build Tailwind CSS workflow completes on main
on:
  workflow_run:
    workflows: ["Build Tailwind CSS"]
    types: [completed]
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    # only run if build-css succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Upload site files
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy to Pages
        uses: actions/deploy-pages@v2
